name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
          - arm-unknown-linux-musleabi
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cross
        run: cargo install cross

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          targets: ${{ matrix.target }}

      - name: Build for ${{ matrix.target }}
        run: cross build --release --target ${{ matrix.target }}

      - name: Strip binary (Linux and macOS)
        if: contains(matrix.target, 'linux') || contains(matrix.target, 'darwin')
        run: |
          strip target/${{ matrix.target }}/release/gh-tree

      - name: Compress binary (Windows)
        if: contains(matrix.target, 'windows')
        run: |
          upx --best target/${{ matrix.target }}/release/gh-tree.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: gh-tree-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/gh-tree*
